=== tnrich/oldVE/FLEX DeviceEditor - src/docs/design.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://jbei.org/device_editor"
    xmlns:de="http://jbei.org/device_editor"
    elementFormDefault="qualified">
    <xs:element name="design">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:version" />
                <xs:element ref="de:sequenceFiles" />
                <xs:element ref="de:partVOs" />
                <xs:element ref="de:eugeneRules" />
                <xs:element ref="de:j5Collection"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="version">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="4.0" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="sequenceFiles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:sequenceFile" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sequenceFile">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:format" />
                <xs:element ref="de:content" />
                <xs:element ref="de:fileName" />
            </xs:sequence>
            <xs:attribute name="hash" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="format">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Genbank" />
                <xs:enumeration value="FASTA" />
                <xs:enumeration value="jbei-seq" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="content" type="xs:string" />
    <xs:element name="fileName" type="xs:string" />
    <xs:element name="partVOs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:partVO" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="partVO">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:name" />
                <xs:group ref="de:seqInfo" minOccurs="0" />
                <xs:element ref="de:parts" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="name" type="xs:string" />
    <xs:group name="seqInfo">
        <xs:sequence>
            <xs:element ref="de:revComp" />
            <xs:element ref="de:startBP" />
            <xs:element ref="de:stopBP" />
            <xs:element ref="de:sequenceFileHash" />
        </xs:sequence>
    </xs:group>
    <xs:element name="revComp" type="xs:boolean" />
    <xs:element name="startBP" type="xs:positiveInteger" />
    <xs:element name="stopBP" type="xs:positiveInteger" />
    <xs:element name="sequenceFileHash" type="xs:string" />
    <xs:element name="parts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:part" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="part">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:fas" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="fas">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="" />
                <xs:enumeration value="DIGEST" />
                <xs:enumeration value="Direct Synthesis" />
                <xs:enumeration value="PCR" />
                <xs:enumeration value="Embed_in_primer_reverse" />
                <xs:enumeration value="Embed_in_primer_forward" />
                <xs:enumeration value="Annealed Oligos"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="eugeneRules">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:eugeneRule" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="eugeneRule">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:name" />
                <xs:element ref="de:negationOperator" />
                <xs:element ref="de:operand1ID" />
                <xs:element ref="de:compositionalOperator" />
                <xs:group ref="de:operand2" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="negationOperator" type="xs:boolean" />
    <xs:element name="operand1ID" type="xs:string" />
    <xs:element name="compositionalOperator">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="AFTER" />
                <xs:enumeration value="BEFORE" />
                <xs:enumeration value="WITH" />
                <xs:enumeration value="THEN" />
                <xs:enumeration value="NEXTTO" />
                <xs:enumeration value="MORETHAN" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:group name="operand2">
        <xs:choice>
            <xs:element ref="de:operand2ID" />
            <xs:element ref="de:operand2Number" />
        </xs:choice>
    </xs:group>
    <xs:element name="operand2ID" type="xs:string" />
    <xs:element name="operand2Number" type="xs:nonNegativeInteger" />
    <xs:element name="j5Collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:isCircular" />
                <xs:element ref="de:j5Bins" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="isCircular" type="xs:boolean" />
    <xs:element name="j5Bins">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:j5Bin" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="j5Bin">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:binName" />
                <xs:element ref="de:iconID" />
                <xs:element ref="de:direction" />
                <xs:element ref="de:dsf" />
                <xs:element ref="de:fro" minOccurs="0" />
                <xs:element ref="de:extra5PrimeBps" minOccurs="0" />
                <xs:element ref="de:extra3PrimeBps" minOccurs="0" />
                <xs:element ref="de:binItems" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="binName" type="xs:string" />
    <xs:element name="iconID">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="assembly_junction" />
                <xs:enumeration value="cds" />
                <xs:enumeration value="five_prime_overhang" />
                <xs:enumeration value="five_prime_utr" />
                <xs:enumeration value="generic" />
                <xs:enumeration value="insulator" />
                <xs:enumeration value="operator_site" />
                <xs:enumeration value="origin_of_replication" />
                <xs:enumeration value="primer_binding_site" />
                <xs:enumeration value="promoter" />
                <xs:enumeration value="protease_site" />
                <xs:enumeration value="protein_stability_element" />
                <xs:enumeration value="restriction_enzyme_recognition_site" />
                <xs:enumeration value="restriction_site_no_overhang" />
                <xs:enumeration value="ribonuclease_site" />
                <xs:enumeration value="rna_stability_element" />
                <xs:enumeration value="signature" />
                <xs:enumeration value="terminator" />
                <xs:enumeration value="three_prime_overhang" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="direction">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="forward" />
                <xs:enumeration value="reverse" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="dsf" type="xs:boolean" />
    <xs:element name="fro" type="xs:int" />
    <xs:element name="extra5PrimeBps" type="xs:int" />
    <xs:element name="extra3PrimeBps" type="xs:int" />
    <xs:element name="binItems">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="de:partID" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="partID" type="xs:string" />
</xs:schema>

=== tnrich/oldVE/biojs/test/data/sbredl/sbredl.xml
<?xml version="1.0" encoding="UTF-8"?>
<de:design xsi:schemaLocation="http://jbei.org/device_editor design.xsd" xmlns:de="http://jbei.org/device_editor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <de:version>4.0</de:version>
  <de:sequenceFiles>
    <de:sequenceFile hash="8f1cbefb1143aa8de5e2a2044acc1fca7cd6135a9b3b6e29ffbf5eae2368cc60">
      <de:format>Genbank</de:format>
      <de:content><![CDATA[LOCUS       TN7R                     265 bp ds-DNA     linear       31-JUL-2012
ACCESSION   TN7R
VERSION     TN7R
KEYWORDS    .
FEATURES             Location/Qualifiers
     misc_feature    21..245
                     /label="Tn7R"
ORIGIN      
        1 ggatgccctg cgtaagcggg tgtgggcgga caataaagtc ttaaactgaa caaaatagat
       61 ctaaactatg acaataaagt cttaaactag acagaatagt tgtaaactga aatcagtcca
      121 gttatgctgt gaaaaagcat actggacttt tgttatggct aaagcaaact cttcattttc
      181 tgaagtgcaa attgcccgtc gtattaaaga ggggcgtggc caagggcatg gtaaagacta
      241 tattcgcggc gttgtgacaa tttac   
//
]]></de:content>
      <de:fileName>TN7R.gbk</de:fileName>
    </de:sequenceFile>
    <de:sequenceFile hash="e0e57544c327251e487207f9c69f0f848f2999760430507eab09796d40f7e93c">
      <de:format>Genbank</de:format>
      <de:content><![CDATA[LOCUS       GentR                    761 bp ds-DNA     linear       31-JUL-2012
ACCESSION   GentR
VERSION     GentR
KEYWORDS    .
FEATURES             Location/Qualifiers
     misc_feature    207..740
                     /label="Gentamycin R"
ORIGIN      
        1 ctgttcggtt cgtaaactgt aatgcaagta gcgtatgcgc tcacgcaact ggtccagaac
       61 cttgaccgaa cgcagcggtg gtaacggcgc agtggcggtt ttcatggctt gttatgactg
      121 tttttttgta cagtctatgc ctcgggcatc caagcagcaa gcgcgttacg ccgtgggtcg
      181 atgtttgatg ttatggagca gcaacgatgt tacgcagcag caacgatgtt acgcagcagg
      241 gcagtcgccc taaaacaaag ttaggtggct caagtatggg catcattcgc acatgtaggc
      301 tcggccctga ccaagtcaaa tccatgcggg ctgctcttga tcttttcggt cgtgagttcg
      361 gagacgtagc cacctactcc caacatcagc cggactccga ttacctcggg aacttgctcc
      421 gtagtaagac attcatcgcg cttgctgcct tcgaccaaga agcggttgtt ggcgctctcg
      481 cggcttacgt tctgcccaag tttgagcagc cgcgtagtga gatctatatc tatgatctcg
      541 cagtctccgg cgagcaccgg aggcagggca ttgccaccgc gctcatcaat ctcctcaagc
      601 atgaggccaa cgcgcttggt gcttatgtga tctacgtgca agcagattac ggtgacgatc
      661 ccgcagtggc tctctataca aagttgggca tacgggaaga agtgatgcac tttgatatcg
      721 acccaagtac cgccacctaa caattcgttc aagccgagat c 
//
]]></de:content>
      <de:fileName>GentR-Casette.gbk</de:fileName>
    </de:sequenceFile>
  </de:sequenceFiles>
  <de:partVOs>
    <de:partVO id="1343751993895362">
      <de:name>t</de:name>
      <de:revComp>false</de:revComp>
      <de:startBP>1</de:startBP>
      <de:stopBP>265</de:stopBP>
      <de:sequenceFileHash>8f1cbefb1143aa8de5e2a2044acc1fca7cd6135a9b3b6e29ffbf5eae2368cc60</de:sequenceFileHash>
      <de:parts>
        <de:part id="1343751993895462">
          <de:fas/>
        </de:part>
      </de:parts>
    </de:partVO>
    <de:partVO id="1343751993895876">
      <de:name>r</de:name>
      <de:revComp>false</de:revComp>
      <de:startBP>1</de:startBP>
      <de:stopBP>761</de:stopBP>
      <de:sequenceFileHash>e0e57544c327251e487207f9c69f0f848f2999760430507eab09796d40f7e93c</de:sequenceFileHash>
      <de:parts>
        <de:part id="1343751993899199">
          <de:fas/>
        </de:part>
      </de:parts>
    </de:partVO>
  </de:partVOs>
  <de:eugeneRules/>
  <de:j5Collection>
    <de:isCircular>true</de:isCircular>
    <de:j5Bins>
      <de:j5Bin>
        <de:binName>0</de:binName>
        <de:iconID>generic</de:iconID>
        <de:direction>forward</de:direction>
        <de:dsf>false</de:dsf>
        <de:binItems>
          <de:partID>1343751993895462</de:partID>
        </de:binItems>
      </de:j5Bin>
      <de:j5Bin>
        <de:binName>1</de:binName>
        <de:iconID>generic</de:iconID>
        <de:direction>forward</de:direction>
        <de:dsf>false</de:dsf>
        <de:binItems>
          <de:partID>1343751993899199</de:partID>
        </de:binItems>
      </de:j5Bin>
    </de:j5Bins>
  </de:j5Collection>
</de:design>

=== tnrich/oldVE/biojs/test/data/DE-XML/Change_column_orienta.xml
<?xml version="1.0" encoding="UTF-8"?>
<de:design xsi:schemaLocation="http://jbei.org/device_editor design.xsd" xmlns:de="http://jbei.org/device_editor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <de:version>4.0</de:version>
  <de:sequenceFiles/>
  <de:partVOs/>
  <de:eugeneRules/>
  <de:j5Collection>
    <de:isCircular>true</de:isCircular>
    <de:j5Bins>
      <de:j5Bin>
        <de:binName>No_Name0</de:binName>
        <de:iconID>promoter</de:iconID>
        <de:direction>forward</de:direction>
        <de:dsf>false</de:dsf>
        <de:binItems/>
      </de:j5Bin>
    </de:j5Bins>
  </de:j5Collection>
</de:design>
